name: CI

on:
  push:
    branches:    
      - main

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    # Standard drop-in approach that should work for most people.
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: python -m pip install -r requirements.txt
        build-command: "sphinx-build -b html / _build"
        docs-folder: "_perguntasdafaq/"
    # Publish built docs to gh-pages branch.
    # ===============================
    - name: Commit documentation changes
      run: |
        git clone https://github.com/ammaraskar/sphinx-action-test.git --branch gh-pages --single-branch gh-pages
        cp -r _perguntasdafaq/_build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # ===============================
